### ISSUE TITLE
Support Keep/Drop rolls

### ISSUE THREAD

**Issue by trescenzi** [Nephos/crystal_pathfinder#2]
In many dice rollers this is supported with `k` and/or `d` short for `keep` and `drop` respectively. Usually these optionally contain `h` or `l` for `highest` and `lowest`. Sometimes `k` defaults to `kh` and `d` defaults to `dl`.

Some examples:
`4d6d1` — roll 4d6 drop the lowest
`2d20k1` — roll 2 d20 keep highest(advantage)
`2d20kl1` — roll 2d20 keep lowest(disadvantage)

I'm happy to implement this but I wanted to make sure that you're on board with it first. Also curious if you think it's worth implementing both or just doing one of the two as you can represent the same thing with either. Advantage could be `2d20dl1` for example.

**Comment by Nephos** [comment]
I didn't know this ! I'm very happy with your proposal !

* `d`, `k` for `drop` and `keep`
* `l` and `h` for `lowest` and `highest`
* if no `l` or `h` specified, we consider `l` as the default value (for both `k` and `d`)

If you don't do it I will anyway ! Very cool idea :)
Thanks !

**Comment by trescenzi** [comment]
Sounds great. I'll take a stab at this today since I have time.

Just for some context. I'm rather new to Crystal but I've been following it for some time as I love Ruby. I'm looking to convert a simple discord dice bot I have [trescenzi/dice-n-easy](https://github.com/trescenzi/dice-n-easy) from Ruby to Crystal now that it's 1.0. Starting with the rolling part since that's simpler than the discord api part haha.

**Comment by Nephos** [comment]
Nice ! I use it myself for a IRC bot. I didn't look at the discord api implementations crystal but I saw some on crystalshards, I bet they are pretty easy If you stick to connect/on message/reply :)

**Comment by Nephos** [comment]
I'll try to merge this noon !
